### ISSUE TITLE
Create UI mockups.

### ISSUE THREAD

**Issue by dantiberi** [dantiberi/Fall-2021-IPRO#4]
As developers, we need to consider how our UI will look and function so we are clear about the goal when we begin developing our product.

**Comment by a-cordell** [comment]
[Jebra_UI_DesignDocument.pdf](https://github.com/dantiberi/Fall-2021-IPRO/files/7255299/Jebra_UI_DesignDocument.pdf)
Created design document with mobile and desktop formats as well as a color scheme.
